const $=id=>document.getElementById(id);let status,selected,detail,busy=false;
async function rpc(payload){const r=await fetch('/memory-isolation/manage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:crypto.randomUUID(),method:'manage',payload})});const data=await r.json();if(!r.ok||!data.result?.ok)throw Error(data.result?.error?.message||'操作失败，请刷新后重试');return data.result.value;}
function node(tag,text,parent){const e=document.createElement(tag);e.textContent=text;parent.append(e);return e;}
async function work(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(e=>e.disabled=true);$('message').textContent='处理中…';try{await fn();$('message').textContent='已完成';}catch(error){$('message').textContent=error.message;}finally{busy=false;document.querySelectorAll('button').forEach(e=>e.disabled=false);}}
async function refresh(){status=await rpc({action:'status'});$('summary').textContent=`自动学习与召回：${status.frozen?'已暂停':'按项目和窗口隔离'}。共享 Noema：${status.noemaEnabled===false?'已停用':status.noemaEnabled===true?'已开启，自动调用仅可提交候选':'状态待确认'}。已有 ${status.windows.length} 个经验窗口。`;$('persona').textContent=status.persona.confirmed?status.persona.changed?'检测到人设与已确认基线不同；请核对是主动修改还是异常变化。':`人设与已确认基线一致（${new Date(status.persona.confirmedAt).toLocaleString()}）。`:'尚无已确认人设基线。';$('persona').className=status.persona.changed?'bad':'good';
 if(status.changedFiles.length){node('p',`检测到 ${status.changedFiles.length} 个技能或程序文件偏离确认版本：`,$('summary'));for(const f of status.changedFiles)node('p',f.path,$('summary'));$('summary').className='box bad';}else{$('summary').className='box';node('small',`已核对 ${status.checkedFiles} 个技能及程序文件，未发现版本变化。`,$('summary'));}
 const old=$('window').value;$('window').replaceChildren();for(const row of status.windows){const o=node('option',`${row.quarantined?'[隔离] ':''}${row.directory||'格式异常'} · ${row.sessionId||row.window.slice(0,12)} · 正式 ${row.approved??0}`,$('window'));o.value=row.project+':'+row.window;}if(!status.windows.length)node('option','暂无经验记录',$('window'));if([...$('window').options].some(x=>x.value===old))$('window').value=old;select();$('limits').textContent=status.limitations;
 $('sources').replaceChildren();const audit=status.sourceAudit;if(audit){node('p',audit.conclusion,$('sources'));for(const item of audit.findings??[])node('p',`${item.level}：${item.text}`,$('sources'));node('small',`核对时间 ${audit.checkedAt}`,$('sources'));}else node('p','暂无导入的历史调查摘要。',$('sources'));
}
function select(){selected=status.windows.find(r=>r.project+':'+r.window===$('window').value);detail=null;$('records').replaceChildren();}
const scope=()=>{if(!selected)throw Error('暂无所选窗口');return {project:selected.project,window:selected.window}};
async function show(){detail=await rpc({action:'detail',...scope()});$('records').replaceChildren();for(const c of detail.candidates){const box=node('div','',$('records'));box.className='box';node('p',`${c.key} · ${c.status} · ${c.integrity?'完整性通过':'内容与批准记录不同'}`,box);node('p',`适用：${c.trigger}\n方法：${c.action}\n不适用：${c.exclusions}`,box);const ep=detail.episodes.find(e=>e.id===c.episodeId);node('p',`来源窗口：${detail.scope.window.id}\n任务：${ep?.task??'缺失'}\n来源：${(ep?.provenance??[]).map(p=>p.kind+' / '+p.reference).join('\n')}`,box);node('p',`记录 ${ep?.at??'未知'} → 候选 ${c.at} → 验证 ${c.validation?.at??'未通过'} → 生效 ${c.approvedAt??'未生效'}`,box);const b=node('button','隔离这条方法',box);b.onclick=()=>work(async()=>{await rpc({action:'method.quarantine',...scope(),id:c.id,revision:detail.revision});await refresh();await show()});if(detail.current[c.key]===c.id){const back=node('button','回退到前一通过版本',box);back.onclick=()=>work(async()=>{await rpc({action:'method.rollback',...scope(),key:c.key,revision:detail.revision});await refresh();await show()});}}
 if(!detail.candidates.length)node('p','暂无候选方法。任务记录和事件链路可导出核对。',$('records'));node('pre',JSON.stringify(detail.events,null,2),$('records'));
}
$('window').onchange=select;$('refresh').onclick=()=>work(refresh);for(const [id,action]of [['freeze','freeze'],['resume','resume']])$(id).onclick=()=>work(async()=>{await rpc({action});await refresh()});$('detail').onclick=()=>work(show);
for(const [id,action]of [['quarantine','window.quarantine'],['unquarantine','window.resume']])$(id).onclick=()=>work(async()=>{await rpc({action,...scope()});await refresh()});
$('confirm').onclick=()=>{if(confirm('确认当前所有主卡、副卡和选择符合你的要求，并替换已确认基线？'))work(async()=>{await rpc({action:'persona.confirm'});await refresh()})};$('restore').onclick=()=>{if(confirm('恢复已确认的人设配置？当前版本会先保存到排查记录中。'))work(async()=>{await rpc({action:'persona.restore',revision:status.persona.currentRevision});await refresh()})};
$('export').onclick=()=>work(async()=>{const data=detail||{status};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='dsh-memory-audit-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});work(refresh);
